name: BuildToga
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=~/theos" >> $GITHUB_ENV
          
      - name: Build Tweak
        run: |
          export THEOS=~/theos
          make package FINALPACKAGE=1
          
      - name: Save Result
        uses: actions/upload-artifact@v4
        with:
          name: MyTweak
          path: packages/*.deb
